export const DAMAGE_TYPE_EMOJI_MAP = new Map<string, string>([
  // --- Physical Damage Types ---
  ["<DT_IMPACT>", "⚒️"],
  ["<DT_IMPACT_OUTLINE>", "⚒️"],
  ["<DT_IMPACT_COLOR>", "⚒️"],
  ["<DT_IMPACT_COLOR_NO_ADV>", "⚒️"],
  ["<DT_PUNCTURE>", "📌"],
  ["<DT_PUNCTURE_OUTLINE>", "📌"],
  ["<DT_PUNCTURE_COLOR>", "📌"],
  ["<DT_PUNCTURE_COLOR_NO_ADV>", "📌"],
  ["<DT_SLASH>", "🗡️"],
  ["<DT_SLASH_OUTLINE>", "🗡️"],
  ["<DT_SLASH_COLOR>", "🗡️"],
  ["<DT_SLASH_COLOR_NO_ADV>", "🗡️"],

  // --- Elemental Damage Types ---
  ["<DT_FIRE>", "🔥"],
  ["<DT_FIRE_OUTLINE>", "🔥"],
  ["<DT_FIRE_COLOR>", "🔥"],
  ["<DT_FIRE_COLOR_NO_ADV>", "🔥"],
  ["<DT_FREEZE>", "❄️"],
  ["<DT_FREEZE_OUTLINE>", "❄️"],
  ["<DT_FREEZE_COLOR>", "❄️"],
  ["<DT_FREEZE_COLOR_NO_ADV>", "❄️"],
  ["<DT_ELECTRICITY>", "⚡️"],
  ["<DT_ELECTRICITY_OUTLINE>", "⚡️"],
  ["<DT_ELECTRICITY_COLOR>", "⚡️"],
  ["<DT_ELECTRICITY_COLOR_NO_ADV>", "⚡️"],
  ["<DT_POISON>", "☠️"],
  ["<DT_POISON_OUTLINE>", "☠️"],
  ["<DT_POISON_COLOR>", "☠️"],
  ["<DT_POISON_COLOR_NO_ADV>", "☠️"],

  // --- Area/Effect Damage Types ---
  ["<DT_EXPLOSION>", "💥"],
  ["<DT_EXPLOSION_OUTLINE>", "💥"],
  ["<DT_EXPLOSION_COLOR>", "💥"],
  ["<DT_EXPLOSION_COLOR_NO_ADV>", "💥"],
  ["<DT_RADIATION>", "☢️"],
  ["<DT_RADIATION_OUTLINE>", "☢️"],
  ["<DT_RADIATION_COLOR>", "☢️"],
  ["<DT_RADIATION_COLOR_NO_ADV>", "☢️"],
  ["<DT_GAS>", "☁️"],
  ["<DT_GAS_OUTLINE>", "☁️"],
  ["<DT_GAS_COLOR>", "☁️"],
  ["<DT_GAS_COLOR_NO_ADV>", "☁️"],
  ["<DT_MAGNETIC>", "🧲"],
  ["<DT_MAGNETIC_OUTLINE>", "🧲"],
  ["<DT_MAGNETIC_COLOR>", "🧲"],
  ["<DT_MAGNETIC_COLOR_NO_ADV>", "🧲"],
  ["<DT_VIRAL>", "🦠"],
  ["<DT_VIRAL_OUTLINE>", "🦠"],
  ["<DT_VIRAL_COLOR>", "🦠"],
  ["<DT_VIRAL_COLOR_NO_ADV>", "🦠"],
  ["<DT_CORROSIVE>", "☣️"],
  ["<DT_CORROSIVE_OUTLINE>", "☣️"],
  ["<DT_CORROSIVE_COLOR>", "☣️"],
  ["<DT_CORROSIVE_COLOR_NO_ADV>", "☣️"],
  ["<DT_RADIANT>", "✨"],
  ["<DT_RADIANT_OUTLINE>", "✨"],
  ["<DT_RADIANT_COLOR>", "✨"],
  ["<DT_RADIANT_COLOR_NO_ADV>", "✨"],
  ["<DT_SENTIENT>", "👁️"],
  ["<DT_SENTIENT_OUTLINE>", "👁️"],
  ["<DT_SENTIENT_COLOR>", "👁️"],

  // --- Special Types ---
  ["<DT_FINISHER>", "⚔️"],
  ["<DT_IMPACT_SPACE>", "⚒️"],
  ["<DT_PUNCTURE_SPACE>", "📍"],
  ["<DT_SLASH_SPACE>", "🔪"],
  ["<DT_FIRE_SPACE>", "🔥"],
  ["<DT_FREEZE_SPACE>", "❄️"],
  ["<DT_ELECTRICITY_SPACE>", "⚛️"],
  ["<DT_POISON_SPACE>", "🧪"],
  ["<LOWER_IS_BETTER>", " "],
])

export const RARITY_SCORES: Record<string, number> = {
  Common: 0,
  Uncommon: 1,
  Rare: 2,
  Legendary: 3,
}

export const TYPE_SCORES: Record<string, number> = {
  "Primary Mod": 0.4,
  "Warframe Mod": 0.5,
  "Shotgun Mod": 0.3,
  "Secondary Mod": 0.2,
  "Melee Mod": 0.1,
}

export const RARITY_COLORS: Record<string, string> = {
  Common: "bg-yellow-700",
  Uncommon: "bg-zinc-400",
  Rare: "bg-amber-300",
  Legendary: "bg-zinc-200",
}
